force-app/main/default/objects/ServiceRequest__c/ServiceRequest__c.object-meta.xml
<CustomObject>
    <description>Case logged</description>
    <label>Service Request</label>
    <nameField>
        <label>ServiceRequest Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service_Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceRequest__c/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Investment</fullName>
            </value>
            <value>
                <fullName>IRA</fullName>
            </value>
            <value>
                <fullName>Trust</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceRequest__c/fields/Funding_Type__c.field-meta.xml
<CustomField>
    <fullName>Funding_Type__c</fullName>
    <label>Funding Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>External Bank</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Transfer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceRequest__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Urgent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceRequest__c/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trust &amp; Investment Onboarding</fullName>
            </value>
            <value>
                <fullName>Money Movement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ServiceRequestApexController.cls
public with sharing class ServiceRequestApexController {
    

    public ServiceRequestApexController() { 
        
    }

   	public class MultiplePickList{
        @AuraEnabled public List<string> acctTypeList;
        @AuraEnabled public List<string> fundTypeList;
        @AuraEnabled public List<string> priorityList;
        @AuraEnabled public List<string> ReqTypeList;
    }

    @AuraEnabled
    public static MultiplePickList GetServiceRequestPickList(){
        MultiplePickList model = new MultiplePickList();
            model.acctTypeList = getPickList(ServiceRequest__c.Account_Type__c.getDescribe().getPicklistValues());
            model.fundTypeList = getPickList(ServiceRequest__c.Funding_Type__c.getDescribe().getPicklistValues());
            model.priorityList = getPickList(ServiceRequest__c.Priority__c.getDescribe().getPicklistValues());
            model.ReqTypeList = getPickList(ServiceRequest__c.Request_Type__c.getDescribe().getPicklistValues());
       return  model; 
    }

     @AuraEnabled
     public static void SaveServiceRequest(ServiceRequest__c model){
          system.debug(model);
          upsert model;
     }


    @TestVisible static List<string> getPickList(List<PicklistEntry> values) {
	List<string> picklist = new List<string>();
        for (PickListEntry entry : values) {
            picklist.add(String.valueOf(entry.getValue()));
        }
        return picklist; //return list
    }
}